For the pancreatitis dataset:

[LOG] n_neighbor = 5
/media/latte/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
/home/rzuo/.local/lib/python3.6/site-packages/fancyimpute/soft_impute.py:100: RuntimeWarning: divide by zero encountered in double_scalars
  return (np.sqrt(ssd) / old_norm) < self.convergence_threshold
Process ForkPoolWorker-1:
Traceback (most recent call last):
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
    self._writer.send_bytes(obj)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 407, in _send_bytes
    self._send(header + buf)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
    self.run()
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
    self._writer.send_bytes(obj)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 407, in _send_bytes
    self._send(header + buf)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Process ForkPoolWorker-2:
Traceback (most recent call last):
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 125, in worker
    put((job, i, result))
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
    self._writer.send_bytes(obj)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 407, in _send_bytes
    self._send(header + buf)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/process.py", line 258, in _bootstrap
    self.run()
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/pool.py", line 130, in worker
    put((job, i, (False, wrapped)))
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/queues.py", line 350, in put
    self._writer.send_bytes(obj)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 203, in send_bytes
    self._send_bytes(m[offset:offset + size])
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 407, in _send_bytes
    self._send(header + buf)
  File "/home/rzuo/.local/lib/python3.6/site-packages/multiprocess/connection.py", line 371, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
